services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.test
    depends_on:
      - database
    networks:
      - backend

  database:
    image: "postgres:16-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.test
    ports:
      - "5433:5432"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge