services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev
    env_file:
      - .env.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      postgres -c listen_addresses='*'

  minio:
        image: minio/minio
        container_name: minio
        ports:
          - "9002:9000"
          - "9003:9001"
        environment:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
          - minio-data:/data
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - postgres
      - minio


volumes:
  postgres-data:
  minio-data: