# Generated by Django 5.1.7 on 2025-04-30 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name=django.core.validators.MinLengthValidator(6)),
        ),
    ]
