# Generated by Django 5.2.1 on 2025-05-19 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_managers_and_more'),
    ]


    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
