# Generated by Django 5.2.1 on 2025-05-19 01:01

import django.core.validators
from django.db import migrations, models

from core.models import User


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        email='admin@adminteste.com',
        password='admin_teste',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
