# Generated by Django 5.1.7 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('question', models.CharField(db_column='tx_question', max_length=200)),
                ('answer', models.CharField(db_column='tx_answer', max_length=200)),
            ],
            options={
                'db_table': 'flashcard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=100)),
                ('content', models.TextField(db_column='tx_content')),
            ],
            options={
                'db_table': 'note',
                'managed': True,
            },
        ),
    ]
