# Generated by Django 5.1.7 on 2025-04-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
                ('description', models.TextField(db_column='tx_description')),
                ('workload', models.IntegerField(db_column='nb_workload')),
            ],
            options={
                'db_table': 'discipline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstitutionRole',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'institution_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'module',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
                ('description', models.TextField(db_column='tx_description')),
                ('id_institution', models.ForeignKey(db_column='fk_institution', on_delete=django.db.models.deletion.CASCADE, to='bit_school.institution')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseModuleDiscipline',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('id_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='bit_school.course')),
                ('id_discipline', models.ForeignKey(db_column='fk_discipline', on_delete=django.db.models.deletion.CASCADE, to='bit_school.discipline')),
                ('id_module', models.ForeignKey(db_column='fk_module', on_delete=django.db.models.deletion.CASCADE, to='bit_school.module')),
            ],
            options={
                'db_table': 'course_module_discipline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInstitutionRole',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('id_institution', models.ForeignKey(db_column='fk_instituition', on_delete=django.db.models.deletion.CASCADE, to='bit_school.institution')),
            ],
            options={
                'db_table': 'user_institution_role',
                'managed': True,
            },
        ),
    ]
