# Generated by Django 5.1.7 on 2025-04-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstitutionrole',
            name='id_institution_role',
            field=models.ForeignKey(blank=True, db_column='fk_institution_role', null=True, on_delete=django.db.models.deletion.CASCADE, to='bit_school.institutionrole'),
        ),
        migrations.AlterField(
            model_name='userinstitutionrole',
            name='id_institution',
            field=models.ForeignKey(blank=True, db_column='fk_institution', null=True, on_delete=django.db.models.deletion.CASCADE, to='bit_school.institution'),
        ),
    ]
