# Generated by Django 5.2.1 on 2025-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_school', '0003_userinstitutionrole_id_institution_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursemodulediscipline',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(db_column='tx_name', default='without_institutional_link', max_length=50),
        ),
        migrations.AlterField(
            model_name='institutionrole',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(db_column='tx_name', default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinstitutionrole',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
