# Generated by Django 5.1.7 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=50)),
                ('description', models.TextField(db_column='tx_description')),
                ('limit_date', models.DateField(db_column='dt_limit_date')),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
                ('description', models.TextField(db_column='tx_description')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'class_member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassRole',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'class_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('day', models.DateField(db_column='dt_day')),
            ],
            options={
                'db_table': 'frequency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('score', models.IntegerField(db_column='nb_score')),
            ],
            options={
                'db_table': 'grade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=50)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('text_response', models.TextField(db_column='tx_text_response')),
                ('file_upload', models.TextField(db_column='tx_file_upload')),
                ('graded', models.BooleanField(db_column='cs_graded')),
            ],
            options={
                'db_table': 'task_submission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(db_column='id_model', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('start_hour', models.DateTimeField(db_column='dt_start_hour')),
                ('end_hour', models.DateTimeField(db_column='dt_end_hour')),
            ],
            options={
                'db_table': 'time',
                'managed': True,
            },
        ),
    ]
