# Generated by Django 5.1.7 on 2025-04-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bit_class', '0001_initial'),
        ('bit_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='id_course_module_discipline',
            field=models.ForeignKey(db_column='fk_course_module_discipline', on_delete=django.db.models.deletion.CASCADE, to='bit_school.coursemodulediscipline'),
        ),
        migrations.AddField(
            model_name='classmember',
            name='id_class',
            field=models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, to='bit_class.class'),
        ),
    ]
