# Generated by Django 5.1.7 on 2025-04-30 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bit_class', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='id_user',
            field=models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classmember',
            name='id_class_role',
            field=models.ForeignKey(db_column='fk_class_role', on_delete=django.db.models.deletion.CASCADE, to='bit_class.classrole'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='id_class_member',
            field=models.ForeignKey(db_column='fk_class_member', on_delete=django.db.models.deletion.CASCADE, to='bit_class.classmember'),
        ),
        migrations.AddField(
            model_name='grade',
            name='id_activity',
            field=models.ForeignKey(db_column='fk_activity', on_delete=django.db.models.deletion.CASCADE, to='bit_class.activity'),
        ),
        migrations.AddField(
            model_name='grade',
            name='id_class_member',
            field=models.ForeignKey(db_column='fk_class_member', on_delete=django.db.models.deletion.CASCADE, to='bit_class.classmember'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='id_activity',
            field=models.ForeignKey(db_column='fk_activity', on_delete=django.db.models.deletion.CASCADE, to='bit_class.activity'),
        ),
        migrations.AddField(
            model_name='time',
            name='id_frequency',
            field=models.ForeignKey(db_column='fk_frequency', on_delete=django.db.models.deletion.CASCADE, to='bit_class.frequency'),
        ),
        migrations.AddField(
            model_name='time',
            name='id_status',
            field=models.ForeignKey(db_column='fk_status', on_delete=django.db.models.deletion.CASCADE, to='bit_class.status'),
        ),
    ]
