# Generated by Django 5.2.1 on 2025-05-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_class', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrole',
            options={'managed': True, 'ordering': ['role']},
        ),
        migrations.RemoveField(
            model_name='classrole',
            name='name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='id_activity',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='id_class_member',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='graded',
        ),
        migrations.AddField(
            model_name='classrole',
            name='role',
            field=models.CharField(choices=[('TCHR', 'Teacher'), ('STD', 'Student'), ('PRIN', 'Principal'), ('TRN', 'Trainee')], db_column='tx_role', default='STD', max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='id_task_submission',
            field=models.ForeignKey(db_column='fk_task_submission', default=1, on_delete=django.db.models.deletion.CASCADE, to='bit_class.tasksubmission'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='delivered',
            field=models.BooleanField(db_column='cs_graded', default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='id_user',
            field=models.ForeignKey(db_column='fk_user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classrole',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(db_column='nb_score', default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='file_upload',
            field=models.URLField(blank=True, db_column='tx_file_upload', null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='text_response',
            field=models.TextField(db_column='tx_text_response', null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClassInvitation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('is_accepted', models.BooleanField(default=False)),
                ('id_class', models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='bit_class.class')),
                ('id_class_role', models.ForeignKey(db_column='fk_role', on_delete=django.db.models.deletion.CASCADE, to='bit_class.classrole')),
            ],
            options={
                'db_table': 'class_invitation',
                'managed': True,
            },
        ),
    ]
