# Generated by Django 5.2.1 on 2025-05-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_class', '0005_alter_class_id_course_module_discipline'),
        ('bit_school', '0004_alter_course_id_alter_coursemodulediscipline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id_course_module_discipline',
            field=models.ForeignKey(db_column='fk_course_module_discipline', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bit_school.coursemodulediscipline'),
        ),
    ]
